##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [3]:
import numpy as np
a=np.array([3,78,3,96],dtype=int)
print("eleman sayısı:",a.size)
print("array boyutu:",a.shape)

eleman sayısı: 4
array boyutu: (4,)


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [6]:
import numpy as np
b=np.array([[1,2,6,7], [4,3,9,5]])
c=np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])

print("b array'inin boyut sayısı:",b.shape)
print("b array'inin eleman sayısı:",b.size)
print("b array'inin satır ve sütun sayısı:",np.shape(b))
print("c array'inin boyut sayısı:",c.shape)
print("c array'inin eleman sayısı:",c.size)
print("c array'inin satır ve sütun sayısı:",np.shape(c))

b array'inin boyut sayısı: (2, 4)
b array'inin eleman sayısı: 8
b array'inin satır ve sütun sayısı: (2, 4)
c array'inin boyut sayısı: (2, 2, 3)
c array'inin eleman sayısı: 12
c array'inin satır ve sütun sayısı: (2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [9]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
b=np.array([[1,2,6,7], [4,3,9,5]])
b[0,1]

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [10]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
b=np.array([[1,2,6,7], [4,3,9,5]])
b[0,3]

7

In [17]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
c=np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
c[1,1,[2]]

array([9])

In [4]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [26]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
b=np.array([[1,2,6,7], [4,3,9,5]])
y=b[0,[1,2]]
print(y)


[2 6]


In [25]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
b=np.array([[1,2,6,7], [4,3,9,5]])
x=b[1,1:]
print(x)

[3 9 5]


In [30]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
c=np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
c[0,1,0:]


array([21,  8, 11])

In [31]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
c=np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
c[1,0,1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [19]:
a=np.zeros((5,3))
b=np.ones((5,3))
birlesik_array=np.concatenate((a,b),axis=0)
print(birlesik_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
